# Generated by Django 4.1.3 on 2023-08-26 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instancia',
            fields=[
                ('id_instancia', models.AutoField(primary_key=True, serialize=False)),
                ('nome_instancia', models.TextField(max_length=100)),
                ('temperatura', models.IntegerField(max_length=10)),
                ('umidade_ar', models.IntegerField(max_length=10)),
                ('umidade_solo', models.IntegerField(max_length=10)),
                ('tipo_solo', models.IntegerField(max_length=10)),
                ('tipo_cultura', models.IntegerField(max_length=10)),
                ('nitrogenio', models.IntegerField(max_length=10)),
                ('potassio', models.IntegerField(max_length=10)),
                ('fosforo', models.IntegerField(max_length=10)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_fertilizante', models.IntegerField(max_length=100)),
                ('data', models.DateField()),
                ('description', models.TextField()),
                ('id_instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizer_predictor.instancia')),
            ],
        ),
    ]
