# Generated by Django 4.1.3 on 2023-08-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizer_predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancia',
            name='fosforo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instancia',
            name='nitrogenio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instancia',
            name='nome_instancia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instancia',
            name='potassio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instancia',
            name='temperatura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instancia',
            name='tipo_cultura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instancia',
            name='tipo_solo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instancia',
            name='umidade_ar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instancia',
            name='umidade_solo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='tipo_fertilizante',
            field=models.IntegerField(),
        ),
    ]
