# Generated by Django 4.1.3 on 2023-09-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizer_predictor', '0002_alter_instancia_fosforo_alter_instancia_nitrogenio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='tipo_fertilizante',
            field=models.TextField(),
        ),
    ]
