# Generated by Django 4.1.3 on 2023-09-13 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizer_predictor', '0003_alter_resultado_tipo_fertilizante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descricao',
            fields=[
                ('id_descricao', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='description',
        ),
        migrations.AddField(
            model_name='resultado',
            name='id_descricao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fertilizer_predictor.descricao'),
        ),
    ]
