# Generated by Django 4.1.3 on 2023-09-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizer_predictor', '0004_descricao_remove_resultado_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descricao',
            name='id_fertilizante',
            field=models.IntegerField(default=1),
        ),
    ]
