# Generated by Django 4.1.3 on 2023-09-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizer_predictor', '0005_descricao_id_fertilizante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricao',
            name='id_fertilizante',
            field=models.IntegerField(),
        ),
    ]
