# Generated by Django 4.1.3 on 2023-10-02 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizer_predictor', '0006_alter_descricao_id_fertilizante'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancia',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
