# Generated by Django 4.1.3 on 2023-10-24 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fertilizer_predictor', '0008_descricaocrop_instanciacrop_resultadocrop'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='id_usuario',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultadocrop',
            name='id_usuario',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
